[tool.poetry]
name = "bifabrik"
version = "0.2.22"
description = "Microsoft Fabric ETL toolbox"
authors = ["Radovan JankoviÄ"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
glob2 = ">=0.7"
pandas = ">=2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
